name: Build Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set short SHA
      id: set_short_sha
      run: echo "GITHUB_SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mock-authentication:${{ env.GITHUB_SHORT_SHA }} .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/mock-authentication:${{ env.GITHUB_SHORT_SHA }}

    - name: Set application name
      id: set_app_name
      run: |
        echo "APP_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
        echo ${{ env.APP_NAME }}

    - name: Clone my helm repository
      run: |
        git clone https://github.com/BENMALEKarim/argocd-helm.git 

    - name: Update Helm values file
      run: |
        docker run --rm -v "$(pwd):/workdir" mikefarah/yq:4 yq e -i ".image.tag = \"${{ env.GITHUB_SHORT_SHA }}\"" /workdir/argocd-helm/apps/${{ env.APP_NAME }}/environments/dev-values.yaml

    - name: Commit and push changes
      run: |
        cd argocd-helm
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "Update image.tag for mock-authentication application in dev environment"
        git push origin main