name: CI pipeline

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - '**/README.md'
      - '**/.gitignore'
      - 'Discussions/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."
  
  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest

    outputs:
      IMAGE_TAG: ${{ steps.set_image_tag.outputs.IMAGE_TAG }}
      APP_NAME: ${{ steps.set_app_name.outputs.APP_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set image tag
      id: set_image_tag
      run: |
        echo "IMAGE_TAG=${GITHUB_SHA::8}-$(basename ${{ github.ref }})" >> $GITHUB_ENV
        echo "IMAGE_TAG=${GITHUB_SHA::8}-$(basename ${{ github.ref }})" >> $GITHUB_OUTPUT

    - name: Set application name
      id: set_app_name
      run: |
        echo "APP_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
        echo "APP_NAME=$(basename ${{ github.repository }})" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}

    - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  update-helm-image-tag:
    needs: docker-build-push
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{needs.docker-build-push.outputs.IMAGE_TAG}}
      APP_NAME: ${{needs.docker-build-push.outputs.APP_NAME}}

    steps:  
    - name: Clone my Helm repository
      run: |
        git clone https://github.com/BENMALEKarim/helm-charts.git

    - name: Update Helm values file
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.image.tag = "${{ env.IMAGE_TAG }}"' -i helm-charts/apps/${{ env.APP_NAME }}/environments/dev-values.yaml

    - name: Commit and push changes
      run: |
        cd helm-charts
        git config user.email ${{ secrets.REPOSITORY_EMAIL }}
        git config user.name ${{ secrets.REPOSITORY_USER }}
        git add .
        git commit -m "Update image.tag for mock-authentication application in dev environment ${{ env.IMAGE_TAG }}"
        git push https://${{ secrets.REPOSITORY_TOKEN }}@github.com/BENMALEKarim/helm-charts.git
