name: Build and Update New feature into DEV environment

on:
  push:
    branches:
      - 'develop'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."
  
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set short SHA
      id: set_short_sha
      run: echo "GITHUB_SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mock-authentication:${{ env.GITHUB_SHORT_SHA }}-$(basename ${{ github.ref }}) .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/mock-authentication:${{ env.GITHUB_SHORT_SHA }}-$(basename ${{ github.ref }})

  update-helm-image-tag:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set application name
      id: set_app_name
      run: |
        echo "APP_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
        echo ${{ env.APP_NAME }}

    - name: Clone my Helm repository
      run: |
        git clone https://github.com/BENMALEKarim/argocd-helm.git

    - name: Install yq
      run: |
        wget https://github.com/mikefarah/yq/releases/download/v4.40.1/yq_linux_amd64 -O /usr/local/bin/yq
        chmod +x /usr/local/bin/yq

    - name: Update Helm values file
      run: |
        yq e -i ".image.tag = \"${{ env.GITHUB_SHORT_SHA }}-$(basename ${{ github.ref }})\"" argocd-helm/apps/${{ env.APP_NAME }}/environments/dev-values.yaml

    - name: Commit and push changes
      run: |
        cd argocd-helm
        rm -rf argocd/
        git config user.email ${{ secrets.REPOSITORY_EMAIL }}
        git config user.name ${{ secrets.REPOSITORY_USER }}
        git add .
        git commit -m "Update image.tag for mock-authentication application in dev environment"
        git push https://${{ secrets.REPOSITORY_TOKEN }}@github.com/BENMALEKarim/argocd-helm.git
