name: Promote Image To Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the application
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.higher_environment }}
    steps:
    - name: promote
      run: |
        echo "Promote $VERSION"