name: Promote Image To Production

on:
  push:
    tags:
    - '**'

jobs:
  get-image-tag:
    runs-on: ubuntu-latest
    env:
      LOW_ENV: stagging
    steps:
    - name: Checkout my Helm repository
      uses: actions/checkout@v4
      with:
        repository: BENMALEKarim/argocd-helm
        path: argocd-helm

    - name: Get Image Tag
      uses: mikefarah/yq@master
      id: get_image_tag
      with:
        cmd: echo "IMAGE_TAG=$(yq eval '.image.tag' 'argocd-helm/apps/mock-authentication/environments/${{ env.LOW_ENV }}-values.yaml')" >> $GITHUB_OUTPUT

    outputs:
      IMAGE_TAG: ${{ steps.get_image_tag.outputs.IMAGE_TAG }}

  docker-tag-push:
    needs: get-image-tag
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{needs.get-image-tag.outputs.IMAGE_TAG}}

    steps:
    - name: Set git tag
      id: set_git_tag
      run: |
        echo "RELEASE_TAG=$(basename ${{ github.ref }})" >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Pull/Tag/Push
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/mock-authentication:${{ env.IMAGE_TAG }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/mock-authentication:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/mock-authentication:${{ env.RELEASE_TAG }}
        docker push ${{ secrets.DOCKER_USERNAME }}/mock-authentication:${{ env.RELEASE_TAG }}