name: Promote Image To Production

on:
  push:
    tags:
    - '**'

jobs:
  docker-tag-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${GITHUB_SHA::8}-$(basename ${{ github.ref }})
      TAG: ${{ github.event_name == 'push' && contains(github.event.ref, 'refs/tags/') && github.event.ref }}

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Pull/Tag/Push
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/mock-authentication:{{ env.IMAGE_TAG }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/mock-authentication:{{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/mock-authentication:{{ env.TAG }}
        docker push ${{ secrets.DOCKER_USERNAME }}/mock-authentication:{{ env.TAG }}
