name: Promote Image To Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Version of the application
        required: true

jobs:
  create-git-tag:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ inputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Create git tag
        run: |
          git config user.email ${{ secrets.REPOSITORY_EMAIL }}
          git config user.name ${{ secrets.REPOSITORY_USER }}
          git tag -a {{ env.TAG }} -m "New Tag: {{ env.TAG }} "
  
  get-image-tag:
    runs-on: ubuntu-latest
    needs: create-git-tag
    env:
      TAG: ${{ inputs.tag }}
      LOW_ENV: stagging
    steps:
    - name: Clone my Helm repository
      run: |
        git clone https://github.com/BENMALEKarim/argocd-helm.git

    - name: Get Image Tag
      uses: mikefarah/yq@master
      id: get_image_tag
      with:
        cmd: echo "IMAGE_TAG=$(yq eval '.image.tag' 'argocd-helm/apps/mock-authentication/environments/${{ env.LOW_ENV }}-values.yaml')" >> $GITHUB_OUTPUT

    outputs:
      IMAGE_TAG: ${{ steps.get_image_tag.outputs.IMAGE_TAG }}

  docker-tag-push:
    needs: get-image-tag
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{needs.get-image-tag.outputs.IMAGE_TAG}}
      TAG: ${{ inputs.tag }}

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Pull/Tag/Push
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/mock-authentication:{{ env.IMAGE_TAG }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/mock-authentication:{{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/mock-authentication:{{ env.TAG }}
        docker push ${{ secrets.DOCKER_USERNAME }}/mock-authentication:{{ env.TAG }}
